### ISSUE TITLE
Implement multifeed#close

### ISSUE THREAD

**Issue by ralphtheninja** [kappa-db/multifeed#10]

**Comment by noffle** [comment]
to wit:

- [ ] close all hypercores (`core.close(cb)`)
- [ ] close all random-access-storage
- [ ] terminate replication streams (error? destroy? end?)
- [ ] decide what to return for the regular API when a multifeed is closed (throw errors?)

**Comment by noffle** [comment]
fixed in 3.0.0

**Comment by noffle** [comment]
The API's behaviour becomes undefined after closing, which we miiiight want to revisit
