### ISSUE TITLE
Question: Will using multi.writer('foo') on two different peers result in a forked feed/hypercore?

### ISSUE THREAD

**Issue by Juul** [kappa-db/multifeed#50]
If peer A creates a new feed with `multi.writer('foo')` and then `feed.append()` and then peer B replicates with peer A before also calling `multi.writer('foo')` and appending to the feed, will they be appending to the same feed, potentially forking the feed, or will they each create their own local feed?

I ask because it looks like I somehow have run into a forked feed situation and I'm wondering if I misunderstood something fundamental.

**Comment by RangerMauve** [comment]
The names are local to each peer, they generate a unique key per peer. The name is there to make it easier to reference locally created feeds by name.

**Comment by noffle** [comment]
Yes! I just updated the README to try and be more explicit about this.
